<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$_enable = Mage::getStoreConfig('ContactPage/settings/enabled', $code);
$_addresses = Mage::helper('ContactPage')->getConfigAddresses();

if ($_enable && $_addresses) {
    $_apikey = Mage::getStoreConfig('ContactPage/settings/api_key', $code);
    $_firstAddress = reset($_addresses);
    $_address =  $_firstAddress['address'];
    $_zoom = Mage::getStoreConfig('ContactPage/settings/zoom', $code);
    $_center_lat = $_firstAddress['latitude'];
    $_center_lng = $_firstAddress['longitude'];
    ?>
    <script type="text/javascript"
            src="//maps.googleapis.com/maps/api/js?<?php if ($_apikey): ?>key=<?php echo $_apikey; ?><?php else: ?>v=3.17<?php endif; ?>"></script>
    <script type="text/javascript">

        var gmarkers = [];
        function initialize() {
            var pos = new google.maps.LatLng(<?php echo $_center_lat; ?>, <?php echo $_center_lng; ?>);
            var mapOptions = {
                center: pos,
                panControl: true,
                zoomControl: true,
                mapTypeControl: true,
                scaleControl: true,
                streetViewControl: true,
                overviewMapControl: true,
                zoom: <?php echo $_zoom; ?>,
            };
            var map = new google.maps.Map(document.getElementById("contact_map"), mapOptions);

            <?php echo 'var locations = '. Mage::helper('ContactPage')->getLocationsForFrontend() . ";\n"; ?>

            var marker, i;
            var infowindow = new google.maps.InfoWindow();


            google.maps.event.addListener(map, 'click', function() {
                infowindow.close();
            });


            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map,
                    icon: locations[i][3]
                });
                gmarkers.push(marker);


                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                    return function() {
                        infowindow.setContent(locations[i][0]);
                        infowindow.open(map, marker);
                    }
                })(marker, i));
            }
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <div id="contact_map" style="min-height: 400px; width: 100%;"></div>
    <div id="addresses" style="display: inline-block">
        <ul>
        <?php foreach ($_addresses as $key => $address): ?>
            <li>
                <?php echo "Address: <a href=\"javascript:google.maps.event.trigger(gmarkers[{$key}],'click');\">{$address['address']}</a>"; ?>
                <?php echo ", Phone: {$address['phone']}"; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>

    <?php
}
?>